- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
    repository_url : "https://gitlab.com/krishna.tiwari/cicd-flask"
    repository_path: "/home/vagrant/CICD-Flask"
  
  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git 
        - python-pip
        - nginx
      
    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'
      